testunbg_mode = true
payment_provider = "stripe"
stripe_api_key_test = ""
stripe_api_key = ""
stripe_link_test = ""
stripe_link = ""
google_client_id = "1020574666762-danm1tkm06ccr8dfg8ahof22adq1nri6.apps.googleusercontent.com"
google_client_secret = "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"
redirect_url_test = ""
redirect_url = ""
